
services:
  api-dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app:cached
      - ~/.nuget/packages:/root/.nuget/packages:ro 
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION_STRING: "Server=database,1433;Database=AirsoftBattleManagementSystem;User Id=sa;Password=K0ciaki!;"
    depends_on:
      - database
      
  api-prod:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION_STRING: "Server=database,1433;Database=AirsoftBattleManagementSystem;User Id=sa;Password=K0ciaki!;"
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "K0ciaki!"
      ACCEPT_EULA: "Y"