
services:
  api-dev:
    build:
      context: .
      target: dev
      dockerfile: src/Dockerfile
    volumes:
      - ./src:/app/src/
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__DefaultConnection: "Server=database,1433;Database=AirsoftBattleManagementSystem;User Id=SA;Password=K0ciaki!;Encrypt=False;"
    depends_on:
      - database
      
  api-prod:
    build:
      context: .
      target: final
      dockerfile: src/Dockerfile
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__DefaultConnection: "Server=database,1433;Database=AirsoftBattleManagementSystem;User Id=SA;Password=K0ciaki!;Encrypt=False;"
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "K0ciaki!"
      ACCEPT_EULA: "Y"